version: '2'
volumes:
    influxdb-data:
    nodered-data:
    grafana-data:
    jupyterlab-data:
services:
  nodered:
    restart: always
    build: ./nodered
    volumes:
      - 'nodered-data:/data'
    ports:
      - "1880:1880"
  influxdb:
    restart: always
    build: ./influxdb
    environment:
      - INFLUXDB_DB=ming_default
    volumes:
      - 'influxdb-data:/data'
    ports:
      - "8086:8086"
  grafana:
    restart: always
    build: ./grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    ports:
      - "80:3000"
    volumes:
      - 'grafana-data:/data'
    depends_on:
      - influxdb
  mosquitto:
    restart: always
    build: ./mosquitto
    ports:
      - "1883:1883"
  jupyterlab:
    restart: always
    build: ./jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - 'jupyterlab-data:/data'

#  bridge:
#    restart: always
#    build: ./bridge
#    depends_on:
#     - influxdb
#     - mosquitto
