apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    database: ming_default
    user: admin
    url: http://influxdb:8086
    jsonData:
      timeInterval: "15s"
    secureJsonData:
      password:
